###

# curl -X 'POST' 
#  'http://localhost:5000/api/auth/register' 
#  -H 'accept: */*' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "email": "shin321@gmail.com",
#  "firstName": "string",
#  "lastName": "string",
#  "password": "string"
#}'
POST http://localhost:5000/api/auth/register
accept: */*
Content-Type: application/json

{
  "email": "shin321@gmail.com",
  "firstName": "string",
  "lastName": "string",
  "password": "string"
}

###

# curl -X 'POST' 
#  'http://localhost:5000/api/auth/login' 
#  -H 'accept: text/plain' 
#  -H 'Content-Type: application/json' 
#  -d '{
#  "email": "string",
#  "password": "string"
#}'
POST http://localhost:5000/api/auth/login
accept: text/plain
Content-Type: application/json

{
  "email": "shin321@gmail.com",
  "password": "string"
}

###

